export const RESET_STATE = "CRUD1_RESET_STATE";
export const CURRENT_ITEM = "CRUD1_CURRENT_ITEM";

export const REQUEST_LOADING = "CRUD1_REQUEST_LOADING";
export const REQUEST_SUCCESS = "CRUD1_REQUEST_SUCCESS";
export const REQUEST_FAILED = "CRUD1_REQUEST_FAILED";

export const CURRENT_ACTION = "CRUD1_CURRENT_ACTION";
export const RESET_ACTION = "CRUD1_RESET_ACTION";
